# **NLP Tutorial: Text Representation - Bag Of Words (BOW)**

In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv("/content/drive/MyDrive/NLP Notes/MY NLP/2. Text Representation (Text Vectrozition)/1. Bag Of Words/spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [71]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [72]:
df["spam"] = df["Category"].apply(lambda x: 1 if x == 'spam' else 0 )

In [73]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [74]:
df.shape

(5572, 3)

# Train test split

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [76]:
X_train

1500    SMS. ac JSco: Energy is high, but u may not kn...
3228         Wife.how she knew the time of murder exactly
3732    Isn't frnd a necesity in life? imagine urself ...
1781    BIG BROTHER ALERT! The computer has selected u...
5511                It‘s reassuring, in this crazy world.
                              ...
4034    I am taking you for italian food. How about a ...
1143    Have you had a good day? Mine was really busy ...
643                  Probably gonna swing by in a wee bit
124     I am going to sao mu today. Will be done only ...
5365    Camera - You are awarded a SiPix Digital Camer...
Name: Message, Length: 4457, dtype: object

In [77]:
X_train.shape

(4457,)

In [78]:
X_test

252     Wen ur lovable bcums angry wid u, dnt take it ...
1523    I thk u dun haf 2 hint in e forum already lor....
5278    URGENT! Your Mobile number has been awarded wi...
3526    I not free today i haf 2 pick my parents up to...
3813           Yep then is fine 7.30 or 8.30 for ice age.
                              ...
214                               Yup... How ü noe leh...
2297    <Forwarded from 21870000>Hi - this is your Mai...
4137                   have you ever had one foot before?
340             U calling me right? Call my hand phone...
1569    Today is ACCEPT DAY..U Accept me as? Brother S...
Name: Message, Length: 1115, dtype: object

In [79]:
X_test.shape

(1115,)

In [80]:
type(X_train)

pandas.core.series.Series

In [81]:
X_train[:4]

1500    SMS. ac JSco: Energy is high, but u may not kn...
3228         Wife.how she knew the time of murder exactly
3732    Isn't frnd a necesity in life? imagine urself ...
1781    BIG BROTHER ALERT! The computer has selected u...
Name: Message, dtype: object

In [82]:
type(X_train.values)

numpy.ndarray


# **Create bag of words representation using CountVectorizer**

In [125]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()


X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58739 stored elements and shape (4457, 7691)>

In [126]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [127]:
X_train_cv.shape

(4457, 7691)

In [132]:
v.get_feature_names_out()[1771]

'chinatown'

In [133]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [131]:
v.vocabulary_

{'sms': 6223,
 'ac': 758,
 'jsco': 3838,
 'energy': 2564,
 'is': 3727,
 'high': 3407,
 'but': 1555,
 'may': 4373,
 'not': 4805,
 'know': 3943,
 'where': 7429,
 '2channel': 377,
 'it': 3738,
 '2day': 378,
 'ur': 7145,
 'leadership': 4035,
 'skills': 6162,
 'strong': 6484,
 'psychic': 5448,
 'reply': 5673,
 'ans': 970,
 'question': 5490,
 'end': 2556,
 'wife': 7456,
 'how': 3496,
 'she': 6037,
 'knew': 3940,
 'the': 6769,
 'time': 6853,
 'of': 4859,
 'murder': 4634,
 'exactly': 2665,
 'isn': 3734,
 'frnd': 2992,
 'necesity': 4705,
 'in': 3617,
 'life': 4081,
 'imagine': 3594,
 'urself': 7158,
 'witout': 7501,
 'hw': 3546,
 'feel': 2781,
 'at': 1107,
 'colleg': 1875,
 'wat': 7337,
 'll': 4140,
 'do': 2354,
 'wth': 7580,
 'cell': 1684,
 'abt': 753,
 'functions': 3021,
 'thnk': 6810,
 'events': 2636,
 'espe': 2615,
 'cared': 1634,
 'missed': 4488,
 'amp': 936,
 'irritated': 3722,
 '4wrd': 519,
 'to': 6885,
 'all': 898,
 'those': 6814,
 'dear': 2171,
 'loving': 4215,
 'frnds': 2993,
 'wthout': 7581,
 'whom': 7444,
 'cant': 1619,
 'live': 4132,
 'jst': 3839,
 'did': 2276,
 'takecare': 6644,
 'goodmorning': 3168,
 'big': 1331,
 'brother': 1508,
 'alert': 885,
 'computer': 1919,
 'has': 3322,
 'selected': 5956,
 'for': 2916,
 '10k': 252,
 'cash': 1651,
 'or': 4943,
 '150': 292,
 'voucher': 7271,
 'call': 1586,
 '09064018838': 199,
 'ntt': 4823,
 'po': 5236,
 'box': 1439,
 'cro1327': 2057,
 '18': 309,
 'bt': 1520,
 'landline': 3990,
 'cost': 2001,
 '150ppm': 298,
 'mobiles': 4524,
 'vary': 7200,
 'reassuring': 5578,
 'this': 6806,
 'crazy': 2042,
 'world': 7546,
 'yes': 7639,
 'come': 1887,
 'nyc': 4843,
 'audiitions': 1129,
 'and': 947,
 'am': 921,
 'trying': 7009,
 'relocate': 5640,
 'chance': 1700,
 'win': 7466,
 '250': 361,
 'every': 2638,
 'wk': 7504,
 'txt': 7041,
 'action': 787,
 '80608': 631,
 'www': 7586,
 'movietrivia': 4593,
 'tv': 7031,
 'custcare': 2104,
 '08712405022': 102,
 '1x150p': 333,
 'dont': 2390,
 'want': 7319,
 'hear': 3356,
 'philosophy': 5157,
 'just': 3855,
 'say': 5885,
 'what': 7419,
 'happen': 3304,
 'gd': 3075,
 'lor': 4184,
 'go': 3140,
 'shopping': 6072,
 'got': 3181,
 'stuff': 6499,
 'wan': 7315,
 'watch': 7338,
 'infernal': 3647,
 'affairs': 829,
 'lar': 4002,
 'hey': 3399,
 'are': 1042,
 'you': 7655,
 'doing': 2377,
 'no': 4772,
 'pa': 5013,
 'will': 7463,
 'be': 1254,
 'really': 5571,
 'pretty': 5369,
 'late': 4010,
 'lesson': 4065,
 'first': 2852,
 'join': 3818,
 'only': 4912,
 'reaching': 5554,
 'tp': 6953,
 'mrt': 4600,
 'each': 2473,
 'moment': 4545,
 'day': 2160,
 'its': 3746,
 'own': 5006,
 'value': 7192,
 'morning': 4571,
 'brings': 1494,
 'hope': 3465,
 'afternoon': 840,
 'faith': 2732,
 'evening': 2633,
 'luv': 4242,
 'night': 4756,
 'rest': 5707,
 'wish': 7486,
 'find': 2834,
 'them': 6775,
 'today': 6890,
 'good': 3163,
 'havent': 3339,
 'stuck': 6489,
 'orchard': 4950,
 'my': 4650,
 'dad': 2123,
 'car': 1627,
 'going': 3152,
 'dinner': 2304,
 'now': 4815,
 'leh': 4056,
 'so': 6243,
 'they': 6790,
 'free': 2964,
 'tonight': 6917,
 'top': 6931,
 'ringtone': 5748,
 'sub': 6510,
 'weekly': 7386,
 'get': 3095,
 '1st': 325,
 'week': 7382,
 'send': 5969,
 'subpoly': 6515,
 '81618': 636,
 'per': 5118,
 'stop': 6451,
 '08718727870': 137,
 'have': 3336,
 'into': 3695,
 'brought': 1510,
 'sun': 6560,
 'shiny': 6052,
 'down': 2405,
 'on': 4902,
 'me': 4382,
 'warming': 7327,
 'heart': 3359,
 'putting': 5476,
 'constant': 1954,
 'smile': 6213,
 'face': 2718,
 'making': 4306,
 'loved': 4206,
 'yup': 7675,
 'more': 4567,
 'already': 910,
 'thanx': 6762,
 'printing': 5383,
 'handing': 3293,
 'up': 7127,
 'tell': 6710,
 'went': 7404,
 'bath': 1229,
 'princess': 5381,
 'toledo': 6902,
 'that': 6765,
 'would': 7558,
 'great': 3217,
 'we': 7358,
 'guild': 3256,
 'could': 2008,
 'meet': 4399,
 'bristol': 1497,
 'road': 5759,
 'somewhere': 6272,
 'touch': 6944,
 'over': 4996,
 'weekend': 7384,
 'our': 4979,
 'plans': 5209,
 'take': 6643,
 'flight': 2873,
 'usually': 7173,
 'body': 1399,
 'takes': 6646,
 'care': 1632,
 'buy': 1560,
 'sure': 6585,
 'doesnt': 2366,
 'progress': 5412,
 'can': 1608,
 'pls': 5227,
 'continue': 1965,
 'talk': 6651,
 'saturday': 5876,
 'home': 3449,
 'by': 1571,
 'way': 7353,
 'started': 6409,
 'pray': 5338,
 'ideas': 3568,
 'anything': 991,
 'see': 5945,
 'help': 3377,
 'guys': 3262,
 'forward': 2942,
 'link': 4112,
 'said': 5841,
 'okay': 4886,
 'sorry': 6292,
 'oh': 4880,
 'wow': 7562,
 'thats': 6768,
 'gay': 3067,
 'firmware': 2850,
 'update': 7132,
 'before': 1281,
 'new': 4740,
 'year': 7629,
 'cos': 1999,
 'yetunde': 7644,
 'wanted': 7321,
 'surprise': 6591,
 'with': 7494,
 'when': 7426,
 'didnt': 2279,
 'money': 4551,
 'returned': 5721,
 'mid': 4445,
 'january': 3769,
 'lt': 4226,
 'gt': 3240,
 'return': 5720,
 'period': 5129,
 'ended': 2557,
 'needs': 4716,
 'dat': 2150,
 'slowly': 6199,
 'vomit': 7266,
 'one': 4906,
 'crab': 2031,
 'was': 7332,
 'running': 5816,
 'sea': 5926,
 'shore': 6074,
 'waves': 7352,
 'came': 1603,
 'cleared': 1815,
 'footprints': 2914,
 'asked': 1085,
 'being': 1291,
 'clearing': 1817,
 'beautiful': 1259,
 'replied': 5672,
 'fox': 2951,
 'following': 2904,
 'catch': 1661,
 'off': 4861,
 'frndsship': 2995,
 'never': 4738,
 'lets': 4068,
 'dwn': 2470,
 'gud': 3246,
 'nyt': 4845,
 'baby': 1180,
 'house': 3492,
 'any': 982,
 'pictures': 5181,
 'facebook': 2719,
 'reach': 5551,
 'office': 4870,
 'around': 1062,
 'decimal': 2184,
 'mobile': 4523,
 'problem': 5397,
 'cann': 1616,
 'voice': 7263,
 'asa': 1075,
 'haha': 3274,
 'heard': 3357,
 'text': 6741,
 're': 5550,
 'ok': 4885,
 'far': 2752,
 'library': 4075,
 'da': 2120,
 'vijay': 7234,
 'jaya': 3777,
 'beerage': 1278,
 'few': 2798,
 'people': 5117,
 'game': 3048,
 'mall': 4310,
 'iouri': 3709,
 'kaila': 3867,
 'haf': 3273,
 'found': 2945,
 'him': 3412,
 'stupid': 6504,
 'cam': 1601,
 'working': 7543,
 'many': 4326,
 'seems': 5951,
 'special': 6323,
 'sight': 6115,
 'very': 7218,
 'remain': 5643,
 'till': 6851,
 'your': 7658,
 'last': 4007,
 'maintain': 4300,
 'ends': 2562,
 'sh': 6014,
 'jas': 3773,
 'ttyl': 7017,
 'everything': 2647,
 'weather': 7367,
 'keep': 3890,
 'extra': 2709,
 'warm': 7326,
 'cold': 1867,
 'nothing': 4809,
 'serious': 5988,
 'lots': 4194,
 'vitamin': 7256,
 'look': 4173,
 'lib': 4073,
 'finish': 2840,
 'yet': 7642,
 'does': 2364,
 'operate': 4930,
 'after': 839,
 'cheers': 1740,
 'card': 1628,
 'god': 3145,
 'love': 4205,
 'limit': 4100,
 'grace': 3197,
 'measure': 4391,
 'power': 5320,
 'boundaries': 1434,
 'endless': 2559,
 'blessings': 1370,
 'always': 919,
 'ni8': 4750,
 'die': 2281,
 'toot': 6927,
 'fringe': 2989,
 'again': 844,
 'hi': 3402,
 'elaine': 2529,
 'meeting': 4401,
 'confirmed': 1937,
 'workin': 7542,
 'oso': 4969,
 'gee': 3078,
 'thgt': 6792,
 'fren': 2974,
 'shop': 6070,
 'still': 6439,
 'weak': 7359,
 'bad': 1186,
 'things': 6796,
 'quick': 5493,
 'please': 5219,
 'keys': 3903,
 'purse': 5468,
 'had': 3271,
 '11': 256,
 'months': 4563,
 'entitled': 2589,
 'latest': 4013,
 'colour': 1878,
 'camera': 1604,
 'co': 1849,
 '08002986030': 52,
 'cool': 1983,
 'pack': 5014,
 'store': 6461,
 'like': 4091,
 'cereals': 1690,
 'if': 3575,
 'must': 4642,
 'food': 2910,
 'gari': 3060,
 'something': 6267,
 '9ja': 723,
 'miss': 4486,
 'dunno': 2463,
 'until': 7125,
 'learn': 4042,
 'pilates': 5187,
 'hello': 3374,
 'wats': 7349,
 'talks': 6655,
 'email': 2541,
 'address': 801,
 'won': 7524,
 'nokia': 4779,
 '7250i': 596,
 'auction': 1128,
 'part': 5059,
 '86021': 666,
 'hg': 3401,
 'suite342': 6548,
 '2lands': 389,
 'row': 5789,
 'w1jhl': 7282,
 '16': 304,
 'erutupalam': 2610,
 'thandiyachu': 6755,
 'congrats': 1941,
 '3g': 450,
 'videophones': 7229,
 'yours': 7662,
 '09061744553': 188,
 'videochat': 7228,
 'wid': 7453,
 'mates': 4356,
 'play': 5211,
 'java': 3775,
 'games': 3049,
 'dload': 2351,
 'polyh': 5269,
 'music': 4639,
 'noline': 4783,
 'rentl': 5664,
 'bx420': 1569,
 'ip4': 3711,
 '5we': 553,
 '150pm': 296,
 'december': 2179,
 '11mths': 265,
 '08002986906': 53,
 'wanna': 7318,
 'gym': 3265,
 'village': 7240,
 'pub': 5453,
 'either': 2525,
 'here': 3389,
 'there': 6783,
 'accordingly': 771,
 'forget': 2924,
 'place': 5199,
 'as': 1074,
 'requests': 5680,
 '1stchoice': 327,
 'uk': 7065,
 'information': 3651,
 '08707808226': 82,
 'transport': 6972,
 'less': 4064,
 'problematic': 5398,
 'than': 6754,
 'sat': 5869,
 'ask': 1083,
 'bday': 1253,
 'need': 4712,
 'definite': 2199,
 'nos': 4801,
 'booking': 1412,
 'fri': 2979,
 'let': 4067,
 'kicks': 3912,
 'were': 7406,
 'sweets': 6614,
 'colours': 1880,
 'quite': 5497,
 'light': 4087,
 'other': 4971,
 'darker': 2140,
 'actually': 792,
 'done': 2388,
 'styling': 6507,
 'hair': 3278,
 'diddy': 2277,
 'neighbor': 4722,
 'comes': 1889,
 'toothpaste': 6929,
 'use': 7163,
 'foreign': 2920,
 'stamps': 6397,
 'country': 2014,
 'lecture': 4049,
 'wonders': 7530,
 '7th': 618,
 '6th': 589,
 'style': 6505,
 '5th': 551,
 '4th': 511,
 'personality': 5140,
 '3rd': 460,
 'nature': 4693,
 '2nd': 398,
 'lovely': 4208,
 'friendship': 2987,
 'sir': 6143,
 'once': 4905,
 'holding': 3443,
 'whole': 7443,
 'appreciated': 1023,
 'two': 7039,
 'having': 3341,
 'map': 4327,
 'reading': 5560,
 'semi': 5967,
 'argument': 1052,
 'apart': 998,
 'from': 2999,
 'lol': 4163,
 'saw': 5884,
 'dollar': 2382,
 'huh': 3521,
 'lei': 4057,
 'used': 7164,
 'driving': 2434,
 'usf': 7167,
 'man': 4312,
 'lot': 4192,
 'stoners': 6449,
 'dint': 2306,
 'slept': 6183,
 'tel': 6705,
 'software': 6249,
 'name': 4669,
 'escape': 2612,
 'theatre': 6770,
 'kavalan': 3884,
 'minutes': 4477,
 'pay': 5089,
 'then': 6777,
 'stock': 6442,
 'comin': 1892,
 'storming': 6463,
 'msg': 4602,
 'wen': 7401,
 'lift': 4086,
 'phne': 5158,
 'knw': 3946,
 'wt': 7577,
 'real': 5562,
 'meaning': 4386,
 'girl': 3117,
 'who': 7441,
 'margaret': 4332,
 'girlfrnd': 3118,
 'grahmbell': 3199,
 'invnted': 3705,
 'telphone': 6715,
 'moral': 4566,
 '4get': 501,
 'person': 5137,
 'his': 3417,
 'back': 1184,
 'work': 7540,
 '2morro': 393,
 'half': 3283,
 'term': 6727,
 '2nite': 401,
 'some': 6258,
 'sexy': 6009,
 'passion': 5073,
 'b4': 1171,
 'chat': 1721,
 '09099726481': 236,
 'dena': 2220,
 'calls': 1600,
 'minmobsmorelkpobox177hp51fl': 4469,
 'yo': 7651,
 'friend': 2984,
 'mine': 4464,
 'lookin': 4176,
 'pick': 5174,
 'later': 4012,
 'winner': 7477,
 'been': 1275,
 'specially': 6327,
 'receive': 5586,
 '1000': 245,
 'holiday': 3444,
 'flights': 2874,
 'inc': 3619,
 'speak': 6321,
 'operator': 4931,
 'claim': 1800,
 '0871277810810': 106,
 'give': 3123,
 'number': 4828,
 'gonna': 3161,
 'soon': 6283,
 'don': 2386,
 'about': 747,
 'anymore': 985,
 've': 7207,
 'cried': 2055,
 'enough': 2579,
 'spare': 6317,
 'supplies': 6577,
 'sleep': 6176,
 'well': 7398,
 'bbq': 1243,
 '6ish': 585,
 'welcome': 7396,
 'think': 6797,
 'disturbing': 2340,
 'her': 3388,
 'slp': 6200,
 'swt': 6622,
 'dreams': 2421,
 'muah': 4618,
 'drinkin': 2427,
 'sending': 5971,
 'greetings': 3225,
 'joy': 3834,
 'happiness': 3313,
 'gr8': 3193,
 'izzit': 3754,
 'raining': 5516,
 'thanks': 6758,
 'tescos': 6734,
 'nice': 4752,
 'gone': 3159,
 'specialisation': 6325,
 'slave': 6175,
 'labor': 3972,
 'month': 4560,
 'sha': 6015,
 'shakara': 6020,
 'beggar': 1283,
 'ready': 5561,
 'tomorrow': 6909,
 'coming': 1893,
 'ic': 3559,
 'should': 6082,
 'doors': 2393,
 'sometime': 6268,
 'make': 4302,
 'pain': 5023,
 'bed': 1268,
 'double': 2398,
 'coins': 1864,
 'factory': 2721,
 'too': 6922,
 'gotta': 3186,
 'nitros': 4768,
 'move': 4588,
 'mind': 4462,
 'bedroom': 1272,
 'minute': 4476,
 'sed': 5944,
 'mood': 4564,
 'out': 4982,
 'minuts': 4478,
 'latr': 4015,
 'cake': 1578,
 'messages': 4434,
 'solve': 6256,
 'case': 1650,
 'murdered': 4635,
 'called': 1593,
 'police': 5263,
 'questioned': 5491,
 'everyone': 2643,
 'sleeping': 6178,
 'took': 6923,
 'cook': 1979,
 'cooking': 1982,
 'gardener': 3059,
 'picking': 5176,
 'vegetables': 7208,
 'maid': 4294,
 'post': 5302,
 'children': 1764,
 'neighbour': 4723,
 'marriage': 4340,
 'arrested': 1066,
 'murderer': 4636,
 'immediately': 3600,
 'reason': 5575,
 'brilliant': 1489,
 'coz': 2025,
 'th': 6753,
 'public': 5454,
 'govt': 3190,
 'instituitions': 3679,
 'closed': 1828,
 'including': 3626,
 'understand': 7090,
 'wnt': 7515,
 'bmw': 1394,
 'urgently': 7150,
 'vry': 7274,
 'urgent': 7149,
 'hv': 3543,
 'shortage': 6076,
 'lacs': 3975,
 'source': 6307,
 'arng': 1059,
 'dis': 2316,
 'amt': 939,
 'prob': 5395,
 'itself': 3747,
 'taking': 6648,
 'sura': 6584,
 'sounds': 6304,
 'posted': 5306,
 'girls': 3120,
 'safe': 5837,
 'selfish': 5960,
 'thank': 6757,
 'hoping': 3472,
 'away': 1162,
 'langport': 3996,
 'town': 6950,
 'he': 3345,
 'searching': 5928,
 'job': 3810,
 'days': 2161,
 'potential': 5311,
 'talent': 6649,
 'yesterday': 7641,
 '750': 601,
 'anytime': 993,
 'network': 4733,
 'mins': 4473,
 'video': 7227,
 'phone': 5160,
 'five': 2857,
 'pounds': 5316,
 '08002888812': 51,
 'delivery': 2214,
 'outside': 4990,
 'islands': 3733,
 'head': 3346,
 'towards': 6949,
 'hard': 3315,
 'rock': 5764,
 'run': 5815,
 'tessy': 6735,
 'favor': 2768,
 'convey': 1974,
 'birthday': 1349,
 'wishes': 7488,
 'nimya': 4763,
 'dnt': 2353,
 'shijas': 6048,
 'bold': 1402,
 'bb': 1239,
 'torch': 6936,
 'boy': 1452,
 'gal': 3043,
 'propsd': 5431,
 'gv': 3263,
 'lv': 4246,
 'lttrs': 4228,
 'threw': 6824,
 'thm': 6809,
 'decided': 2182,
 'aproach': 1033,
 'dt': 2451,
 'truck': 6999,
 'speeding': 6333,
 'wn': 7514,
 'hit': 3419,
 'ran': 5527,
 'hell': 3372,
 'saved': 5881,
 'cn': 1845,
 'fast': 2756,
 'boost': 1417,
 'secret': 5935,
 'instantly': 3677,
 'shouted': 6085,
 'thy': 6840,
 'lived': 4133,
 'happily': 3312,
 '2gthr': 384,
 'drinking': 2428,
 'evrydy': 2661,
 'story': 6464,
 'msgs': 4607,
 'famamus': 2740,
 'fffff': 2800,
 'kadeem': 3865,
 'gave': 3066,
 'photo': 5165,
 'registered': 5626,
 'ah': 854,
 'tmr': 6880,
 'yck': 7627,
 'movie': 4591,
 'collect': 1871,
 'oredi': 4954,
 'laptop': 4001,
 'noe': 4775,
 'infra': 3653,
 'slow': 6196,
 'brainy': 1463,
 'paper': 5043,
 'morn': 4569,
 'aft': 838,
 'cbe': 1670,
 'nowadays': 4817,
 'showrooms': 6094,
 'city': 1797,
 'shaping': 6030,
 'drms': 2436,
 'aight': 864,
 'informed': 3652,
 'noon': 4789,
 'themob': 6776,
 'premium': 5353,
 'pink': 5190,
 'panther': 5038,
 'sugababes': 6541,
 'zebra': 7679,
 'animation': 956,
 'badass': 1187,
 'hoody': 3460,
 'wallpaper': 7310,
 'felt': 2791,
 'conveying': 1975,
 'ese': 2613,
 'werethe': 7408,
 'monkeespeople': 4552,
 'monkeyaround': 4554,
 'howdy': 3499,
 'gorgeous': 3177,
 'howu': 3502,
 'doin': 2375,
 'foundurself': 2946,
 'jobyet': 3812,
 'sausage': 5878,
 'jen': 3787,
 'xxx': 7604,
 'deleted': 2208,
 'old': 4894,
 'website': 7372,
 'blogging': 1376,
 'magicalsongs': 4290,
 'blogspot': 1377,
 'com': 1881,
 'thk': 6807,
 'juz': 3861,
 'accordin': 770,
 'discussed': 2329,
 'yest': 7640,
 'except': 2669,
 'kb': 3887,
 'nt': 4820,
 'much': 4619,
 'attend': 1118,
 'fixed': 2860,
 'test': 6736,
 'message': 4432,
 'darlin': 2143,
 'wait': 7296,
 'fran': 2954,
 'ps': 5442,
 'dirty': 2315,
 'anal': 944,
 'sex': 6005,
 '10': 243,
 'gang': 3053,
 'bang': 1204,
 'finally': 2832,
 'completed': 1912,
 'course': 2020,
 'wahala': 7290,
 'remember': 5646,
 'kiss': 3930,
 'sound': 6302,
 'effects': 2511,
 'kind': 3921,
 'brighten': 1488,
 'dance': 2132,
 'river': 5758,
 'hows': 3501,
 'favourite': 2771,
 'couldn': 2010,
 'nite': 4766,
 'nearly': 4704,
 'rang': 5532,
 '30': 415,
 'lmao': 4143,
 'wont': 7531,
 'needing': 4715,
 'persons': 5141,
 'fair': 2731,
 '09063458130': 193,
 'polyph': 5270,
 '150p': 294,
 'eh': 2519,
 'wrongly': 7574,
 'stitch': 6441,
 'trouser': 6997,
 'wa': 7285,
 'efficient': 2512,
 'unlimited': 7114,
 'texts': 6751,
 'limited': 4101,
 'ducking': 2454,
 'chinchillas': 1772,
 'mr': 4597,
 'owl': 5005,
 'licks': 4077,
 'short': 6075,
 'cute': 2110,
 'try': 7008,
 'prove': 5435,
 '945': 712,
 'seen': 5952,
 'friday': 2980,
 'getting': 3103,
 'goods': 3173,
 'common': 1898,
 'better': 1314,
 'china': 1770,
 'asia': 1081,
 'expensive': 2692,
 'holla': 3445,
 'both': 1428,
 'happy': 3314,
 'battery': 1235,
 'low': 4217,
 'successful': 6528,
 'us': 7159,
 'error': 2608,
 'tyler': 7052,
 ...}

In [117]:
X_train_cv[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 23 stored elements and shape (1, 7691)>

In [99]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [100]:
np.where(X_train_np[0]!=0)

(array([ 377,  378,  758,  970, 1555, 2556, 2564, 3407, 3727, 3738, 3838,
        3943, 4035, 4373, 4805, 5448, 5490, 5673, 6162, 6223, 6484, 7145,
        7429]),)

In [119]:
X_train[:4][1500]

'SMS. ac JSco: Energy is high, but u may not know where 2channel it. 2day ur leadership skills r strong. Psychic? Reply ANS w/question. End? Reply END JSCO'

In [120]:
X_train_np[0][377]

np.int64(1)


# **Train the naive bayes model**

In [121]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

 **In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.**
**On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.**

In [134]:
X_test_cv = v.transform(X_test)


# **Evaluate Performance**

In [124]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       965
           1       0.98      0.96      0.97       150

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [136]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])


# **Train the model using sklearn pipeline and reduce number of lines of code**

In [137]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [138]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [139]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       965
           1       0.98      0.96      0.97       150

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115